"""Change FK constraints in download and view records to materials_dataset

Revision ID: d995a8d9859e
Revises: 003
Create Date: 2025-12-01 09:00:41.273768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd995a8d9859e'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook')
    op.drop_table('uvl_dataset')
    with op.batch_alter_table('ds_download_record', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ds_download_record_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'materials_dataset', ['dataset_id'], ['id'])

    with op.batch_alter_table('ds_view_record', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ds_view_record_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'materials_dataset', ['dataset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_view_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ds_view_record_ibfk_1'), 'data_set', ['dataset_id'], ['id'])

    with op.batch_alter_table('ds_download_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ds_download_record_ibfk_1'), 'data_set', ['dataset_id'], ['id'])

    op.create_table('uvl_dataset',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ds_meta_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['ds_meta_data_id'], ['ds_meta_data.id'], name=op.f('uvl_dataset_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('uvl_dataset_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('webhook',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
