"""Fakenodo depositions

Revision ID: 44b375f6f3a4
Revises: eda0c880820f
Create Date: 2025-11-10 11:33:43.463755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b375f6f3a4'
down_revision = 'eda0c880820f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dep_metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('doi', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deposition')
    # ### end Alembic commands ###